name: CI/CD Build Tests

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '30 3 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['16', '18']
    name: ${{ matrix.os }} - Node ${{ matrix.node }} Test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Set up Node
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install Dependencies
      run: yarn
    - name: Execute Unit Tests
      run: yarn test
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        PGSQL_HOST: ${{ secrets.PGSQL_HOST }}
        PGSQL_USER: ${{ secrets.PGSQL_USER }}
        PGSQL_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
        PGSQL_DATABASE: ${{ secrets.PGSQL_DATABASE }}
        SQL_TABLE: ${{ matrix.os }}-${{ matrix.node }}-${{ github.sha }}-${{ github.event_name }}
    - name: Publish to NPM
      if: matrix.node == '16' && matrix.os == 'ubuntu-latest' && github.event_name == 'release'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
